### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by Pavkazzz** [Mikerah/GenreExplorer#1]
Hi, i'm trying to start server with `python3 manage.py runserver` and get error:

`from .constants import LIST_OF_LETTERS
ImportError: No module named 'genres.constants'
`

**Comment by Pavkazzz** [comment]
File "GenreExplorer\genre_explorer\genres\genres_scraper.py", line 2, in <module>

What is .constants and how i can get it?
thx.

**Comment by Mikerah** [comment]
I removed by Youtube Data API Key and added the constants.py file.
